name: Release

on:
  release:
    types: [published]

env:
  NODE_VERSION: '22'

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          npm run lint
          npm run type-check
          npm run test:unit
          npm run build

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## What's Changed
            
            This release includes:
            - Bug fixes and improvements
            - Updated dependencies
            - Enhanced documentation
            
            ## Installation
            
            ```bash
            npm install aws-testing-framework@${{ github.ref_name }}
            ```
            
            ## Documentation
            
            - [Getting Started](https://github.com/sophiegle/aws-testing-framework/blob/main/docs/GETTING_STARTED.md)
            - [API Documentation](https://github.com/sophiegle/aws-testing-framework/blob/main/docs/API.md)
            - [Example Project](https://github.com/sophiegle/aws-testing-framework-test)
          draft: false
          prerelease: false 